services:
  db:
    image: postgres:15
    container_name: task-db
    restart: always
    environment:
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: npg_yQi7TKV5PIAc
      POSTGRES_DB: neondb
    ports:
      - "5432:5432"
    volumes:
      - task_db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: task-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://neondb_owner:npg_yQi7TKV5PIAc@db:5432/neondb"
    depends_on:
      - db

volumes:
  task_db_data:
